
Exception in thread "main" java.util.InputMismatchException
	at java.util.Scanner.throwFor(Scanner.java:864)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextLong(Scanner.java:2222)
	at java.util.Scanner.nextLong(Scanner.java:2182)
	at Main.run(Main.java:14)
	at Main.main(Main.java:9)
