Total Instances: 81

Total Correct: 1
Total Runtime Failed: 26
Total Compilation Failed: 8
Total Test Failed: 45
Total Infinite Loop: 1

Accuracy: 1.2345679012345678
Runtime Rate: 32.098765432098766
Compilation Rate: 9.876543209876543
Test Failed Rate: 55.55555555555556
Infinite Loop Rate: 1.2345679012345678

=================================================================================================
Failed Test Files: ['codeforces_190_A.py', 'codeforces_651_A.py', 'codeforces_110_B.py', 'atcoder_ABC124_C.py', 'atcoder_AGC046_B.py', 'atcoder_ABC164_A.py', 'atcoder_AGC046_A.py', 'atcoder_ABC043_B.py', 'atcoder_ABC143_A.py', 'atcoder_ABC120_C.py', 'codeforces_32_B.py', 'codeforces_58_B.py', 'atcoder_ABC149_B.py', 'atcoder_ABC178_A.py', 'atcoder_ABC132_F.py', 'atcoder_ABC142_A.py', 'codeforces_459_A.py', 'codeforces_49_A.py', 'atcoder_ABC169_D.py', 'codeforces_514_A.py', 'codeforces_373_B.py', 'codeforces_546_A.py', 'codeforces_579_A.py', 'atcoder_ABC158_B.py', 'atcoder_ABC158_A.py', 'atcoder_ARC062_B.py', 'codeforces_340_A.py', 'codeforces_86_A.py', 'atcoder_ABC136_B.py', 'codeforces_276_B.py', 'codeforces_242_A.py', 'atcoder_ABC127_B.py', 'atcoder_ABC178_B.py', 'codeforces_672_A.py', 'atcoder_ABC149_C.py', 'atcoder_ABC108_B.py', 'codeforces_622_A.py', 'atcoder_ABC151_A.py', 'atcoder_ABC125_A.py', 'codeforces_379_A.py', 'codeforces_59_A.py', 'codeforces_96_B.py', 'atcoder_ABC174_C.py', 'codeforces_92_A.py', 'codeforces_581_A.py'] 
Failed Test Details: ['Filename: codeforces_58_B.py Actual: 733035\n244345\n48869\n1\n-36 Generated: 733035\n244345\n48869\n1\n', 'Filename: atcoder_AGC046_B.py Actual: -2 Generated: 17\n', 'Filename: atcoder_ABC120_C.py Actual: -27 Generated: 0\n', 'Filename: atcoder_ABC108_B.py Actual: 3 10 -1 7 -80 Generated: 3 10 -1 7\n', 'Filename: codeforces_340_A.py Actual: 1000000044 Generated: 1000000000\n', 'Filename: atcoder_ABC125_A.py Actual: -46 Generated: 0\n', 'Filename: atcoder_ABC132_F.py Actual: 217 Generated: 1000\n', 'Filename: codeforces_379_A.py Actual: 146 Generated: 80\n', 'Filename: atcoder_ABC149_B.py Actual: -49 1000000000008 Generated: 0 1000000000000\n', 'Filename: atcoder_ABC149_C.py Actual: 9513 Generated: 9587\n', 'Filename: codeforces_242_A.py Actual: 73\n3 2\n4j 2\n43\nUH2\nYz(\n45 4 Generated: 6\n3 2\n4 2\n4 3\n5 2\n5 3\n5 4\n', 'Filename: atcoder_AGC046_A.py Actual: 276 Generated: Input must be a single integer.\n', 'Filename: atcoder_ABC174_C.py Actual: 18 Generated: -1\n', 'Filename: atcoder_ABC124_C.py Actual: 54 Generated: 0\n', 'Filename: codeforces_110_B.py Actual: ar;dabcda}cdabcd}bcsaWcd5bcda=cdabcdabc`aOcdab4dabodabcdafcdabcwabcdabcdabcdabgdabud[bcdabAdaocd2bkd Generated: abcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\n', 'Filename: atcoder_ARC062_B.py Actual: 82 Generated: 0\n', 'Filename: codeforces_92_A.py Actual: -41 Generated: 9\n', 'Filename: atcoder_ABC169_D.py Actual: 9 Generated: 10\n', 'Filename: codeforces_622_A.py Actual: 344 Generated: 311\n', 'Filename: codeforces_459_A.py Actual: 4 4 0 Generated: 4 4 0 0\n', 'Filename: codeforces_579_A.py Actual: 48 Generated: 2\n', 'Filename: codeforces_651_A.py Actual: 38 Generated: 122\n', 'Filename: codeforces_546_A.py Actual: -60 Generated: 0\n', 'Filename: codeforces_86_A.py Actual: -60 Generated: 0\n', 'Filename: atcoder_ABC164_A.py Actual: unRsafe Generated: unsafe\n', 'Filename: atcoder_ABC142_A.py Actual: 27.935654253757406 Generated: 0.5\n', 'Filename: atcoder_ABC143_A.py Actual: -27 Generated: 25\n', 'Filename: codeforces_276_B.py Actual: SeconBd Generated: Second\n', 'Filename: atcoder_ABC178_A.py Actual: 25 Generated: 1\n', 'Filename: atcoder_ABC136_B.py Actual: 90933 Generated: 90909\n', 'Filename: atcoder_ABC127_B.py Actual: 17\n0\n11\n28\n59\n51\n132\n258\n526\n929 Generated: 3\n5\n9\n17\n33\n65\n129\n257\n513\n1025\n', 'Filename: codeforces_49_A.py Actual: N Generated: NO\n', 'Filename: atcoder_ABC043_B.py Actual: 78 Generated: 0000000000\n', 'Filename: codeforces_96_B.py Actual: 4444477694 Generated: ', 'Filename: atcoder_ABC151_A.py Actual: O Generated: 100\n', 'Filename: codeforces_672_A.py Actual: 55 Generated: 3\n', 'Filename: codeforces_581_A.py Actual: -51 -57 Generated: 45 27\n', 'Filename: codeforces_190_A.py Actual: 96 154 -55 Generated: 96 154\n', 'Filename: atcoder_ABC178_B.py Actual: -186233282690604537 Generated: -186233282690604452\n', "Filename: codeforces_59_A.py Actual: VS?Z]#CVVVH@y@VB=?HO-7(152g1JC~(MyQ0^oWWw]xVx&uO2N#oUVgiDQwK^M;?9TcYuTlq4SQ.cj:|+qlxpsp[PmW .k`NWT' Generated: CDOZDPBVVVHNBJVBYHEOXWFLJKRWJCAJMIFCOZWWYFKVWOGTVJCUUSIGDQFKUMEWJTDYITVEEIAYBWRHOMRWMPDIPJWIUXFNWUZ\n", 'Filename: codeforces_373_B.py Actual: 635558 Generated: 635520\n', 'Filename: codeforces_32_B.py Actual: 54 Generated: 00\n', 'Filename: atcoder_ABC158_B.py Actual: 370614275896614948 Generated: 370614275896614890\n', 'Filename: atcoder_ABC158_A.py Actual: Yzes Generated: Yes\n', 'Filename: codeforces_514_A.py Actual: 4304 Generated: 4221\n'] 
=================================================================================================
Runtime Error Files: ['codeforces_678_A.py', 'atcoder_ABC169_C.py', 'atcoder_ABC051_A.py', 'codeforces_147_A.py', 'codeforces_544_B.py', 'atcoder_ABC139_B.py', 'atcoder_ARC102_C.py', 'atcoder_ABC132_A.py', 'codeforces_189_A.py', 'codeforces_8_B.py', 'codeforces_569_A.py', 'atcoder_AGC006_B.py', 'atcoder_ABC153_A.py', 'atcoder_ABC155_E.py', 'codeforces_30_A.py', 'codeforces_171_A.py', 'codeforces_79_A.py', 'atcoder_ABC122_D.py', 'atcoder_ABC114_C.py', 'codeforces_99_A.py', 'atcoder_ABC168_C.py', 'atcoder_ABC170_A.py', 'atcoder_ABC070_B.py', 'codeforces_369_B.py', 'atcoder_ABC124_A.py', 'codeforces_334_A.py'] 
Runtime Error Details: ['Filename: codeforces_544_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_544_B.py", line 2, in <module>\n    printIsland(n, count)\nNameError: name \'printIsland\' is not defined\n', 'Filename: codeforces_369_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_369_B.py", line 3, in <module>\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'1 1 1 1 1 1\'\n', 'Filename: atcoder_ABC070_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC070_B.py", line 13, in <module>\n    if array[i] == 2:\nNameError: name \'array\' is not defined\n', 'Filename: atcoder_ARC102_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ARC102_C.py", line 8, in <module>\n    nchoosek[i][j] = (nchoosek[i - 1][j] + nchoosek[i - 1][j - 1]) % mod\nIndexError: list index out of range\n', 'Filename: codeforces_678_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_678_A.py", line 1, in <module>\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'999999999 1\'\n', 'Filename: atcoder_AGC006_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_AGC006_B.py", line 31, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_AGC006_B.py", line 4, in main\n    for _ in range(int(input())):\nValueError: invalid literal for int() with base 10: \'2 1\'\n', 'Filename: atcoder_ABC114_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC114_C.py", line 4, in <module>\n    S = input()\nEOFError: EOF when reading a line\n', 'Filename: atcoder_ABC170_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 14, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 4, in main\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'1 2 3 4 0\'\n', 'Filename: codeforces_189_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_189_A.py", line 16, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_189_A.py", line 4, in main\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'29 27 18 2\'\n', 'Filename: atcoder_ABC122_D.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 35, in <module>\n    ins = atcoder_ABC122_D()\nNameError: name \'atcoder_ABC122_D\' is not defined\n', 'Filename: codeforces_99_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_99_A.py", line 23, in <module>\n    tests = int(input())\nValueError: invalid literal for int() with base 10: \'8.3\'\n', 'Filename: atcoder_ABC153_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC153_A.py", line 1, in <module>\n    monsterHP = int(input())\nValueError: invalid literal for int() with base 10: \'10000 1\'\n', 'Filename: codeforces_30_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_30_A.py", line 3, in <module>\n    A = int(input())\nValueError: invalid literal for int() with base 10: \'7 896 7\'\n', 'Filename: codeforces_147_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_147_A.py", line 16, in <module>\n    sb = StringBuilder()\nNameError: name \'StringBuilder\' is not defined\n', 'Filename: atcoder_ABC132_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC132_A.py", line 59, in <module>\n    s = sc.next()\nAttributeError: \'dict\' object has no attribute \'next\'\n', 'Filename: atcoder_ABC139_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC139_B.py", line 1, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'8 8\'\n', 'Filename: codeforces_79_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_79_A.py", line 41, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_79_A.py", line 9, in main\n    with open(\'input.txt\', \'r\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'input.txt\'\n', 'Filename: codeforces_171_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_171_A.py", line 8, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'35005211 521595368\'\n', 'Filename: atcoder_ABC124_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC124_A.py", line 11, in <module>\n    print(solve())\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC124_A.py", line 2, in solve\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'6 6\'\n', 'Filename: codeforces_334_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_334_A.py", line 20, in <module>\n    print(odd.pop(0) + " " + even.pop(), end=" ")\nTypeError: unsupported operand type(s) for +: \'int\' and \'str\'\n', 'Filename: atcoder_ABC169_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC169_C.py", line 11, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC169_C.py", line 4, in main\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'814793613347395 1.99\'\n', 'Filename: atcoder_ABC155_E.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC155_E.py", line 36, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC155_E.py", line 31, in main\n    dp[i] = get_dp(c[i], i, 0)\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC155_E.py", line 19, in get_dp\n    dp[0][i] = min(dp[0][i], dp[i+1][j] + tmp + k)\nIndexError: list index out of range\n', 'Filename: codeforces_569_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_569_A.py", line 18, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_569_A.py", line 11, in main\n    t = int(input())\nValueError: invalid literal for int() with base 10: \'100000 3125 2\'\n', 'Filename: atcoder_ABC168_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC168_C.py", line 3, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'1 2 9 49\'\n', 'Filename: codeforces_8_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_8_B.py", line 40, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_8_B.py", line 18, in main\n    co[0][k] = x\nIndexError: list assignment index out of range\n', 'Filename: atcoder_ABC051_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 8, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 4, in main\n    a, b, c = sys.stdin.readline().strip().split()\nValueError: not enough values to unpack (expected 3, got 1)\n'] 
=================================================================================================
Compilation Error Files: ['codeforces_55_A.py', 'atcoder_AGC025_A.py', 'codeforces_203_A.py', 'atcoder_AGC002_A.py', 'codeforces_678_B.py', 'atcoder_ABC172_D.py', 'codeforces_306_A.py', 'atcoder_AGC007_C.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_669_A.py'] 
=================================================================================================
