Total Instances: 81

Total Correct: 0
Total Runtime Failed: 2
Total Compilation Failed: 57
Total Test Failed: 21
Total Infinite Loop: 1

Accuracy: 0.0
Runtime Rate: 2.4691358024691357
Compilation Rate: 70.37037037037037
Test Failed Rate: 25.925925925925924
Infinite Loop Rate: 1.2345679012345678

=================================================================================================
Failed Test Files: ['codeforces_276_B.py', 'codeforces_306_A.py', 'codeforces_59_A.py', 'codeforces_622_A.py', 'atcoder_ABC043_B.py', 'codeforces_49_A.py', 'atcoder_AGC046_B.py', 'atcoder_ABC108_B.py', 'atcoder_ABC155_E.py', 'atcoder_ABC149_B.py', 'codeforces_672_A.py', 'atcoder_ABC070_B.py', 'atcoder_ABC178_B.py', 'atcoder_ABC132_F.py', 'atcoder_ABC169_D.py', 'atcoder_AGC002_A.py', 'atcoder_ABC168_C.py', 'atcoder_ABC172_D.py', 'codeforces_373_B.py', 'atcoder_ABC136_B.py', 'atcoder_ABC124_A.py'] 
Failed Test Details: ['Filename: atcoder_ABC043_B.py Actual: 78 Generated: 0000000000\n', 'Filename: atcoder_ABC172_D.py Actual: 837779626111797 Generated: 837779626111757\n', 'Filename: atcoder_ABC136_B.py Actual: 90933 Generated: 90909\n', 'Filename: atcoder_AGC002_A.py Actual: Postive Generated: Negative\n', 'Filename: codeforces_373_B.py Actual: 635558 Generated: 635520\n', "Filename: codeforces_59_A.py Actual: VS?Z]#CVVVH@y@VB=?HO-7(152g1JC~(MyQ0^oWWw]xVx&uO2N#oUVgiDQwK^M;?9TcYuTlq4SQ.cj:|+qlxpsp[PmW .k`NWT' Generated: CDOZDPBVVVHNBJVBYHEOXWFLJKRWJCAJMIFCOZWWYFKVWOGTVJCUUSIGDQFKUMEWJTDYITVEEIAYBWRHOMRWMPDIPJWIUXFNWUZ\n", 'Filename: atcoder_ABC178_B.py Actual: -186233282690604537 Generated: -186233282690604452\n', 'Filename: codeforces_276_B.py Actual: SeconBd Generated: Second\n', 'Filename: codeforces_49_A.py Actual: N Generated: Y\n', 'Filename: atcoder_ABC155_E.py Actual: -1 Generated: 1\n', 'Filename: atcoder_ABC108_B.py Actual: 3 10 -1 7 -80 Generated: 3 10 -1 7\n', 'Filename: atcoder_ABC070_B.py Actual: -21 Generated: 0\n', 'Filename: atcoder_ABC132_F.py Actual: 217 Generated: 147\n', 'Filename: atcoder_AGC046_B.py Actual: -2 Generated: 65\n', 'Filename: atcoder_ABC149_B.py Actual: -49 1000000000008 Generated: 0 1000000000000\n', 'Filename: atcoder_ABC124_A.py Actual: 61 Generated: 12\n', 'Filename: codeforces_672_A.py Actual: 55 Generated: 3\n', 'Filename: codeforces_306_A.py Actual: 94 -94 43 12 56 -8 101 21 92 -19 68 -19 -89 -66 30 79 92 -53 -88 -65 -88 -23 -38 -62 -66 69 -30 -28 -46 -81 -79 49 -51 76 Generated: 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ', 'Filename: codeforces_622_A.py Actual: 344 Generated: 311\n', 'Filename: atcoder_ABC168_C.py Actual: -45.96915777646216 Generated: 1.000076150972172\n', 'Filename: atcoder_ABC169_D.py Actual: 9 Generated: 10\n'] 
=================================================================================================
Runtime Error Files: ['codeforces_189_A.py', 'codeforces_30_A.py'] 
Runtime Error Details: ['Filename: codeforces_30_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/wizardcoder/avatar/java/python-sanitized/codeforces_30_A.py", line 21, in <module>\n    A = int(input())\nValueError: invalid literal for int() with base 10: \'7 896 7\'\n', 'Filename: codeforces_189_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/wizardcoder/avatar/java/python-sanitized/codeforces_189_A.py", line 64, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/wizardcoder/avatar/java/python-sanitized/codeforces_189_A.py", line 52, in main\n    n = in_.nextInt()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/wizardcoder/avatar/java/python-sanitized/codeforces_189_A.py", line 48, in nextInt\n    return int(self.scanner.readline())\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/wizardcoder/avatar/java/python-sanitized/codeforces_189_A.py", line 10, in readline\n    self.buf += self.stream.read(1).decode()\nAttributeError: \'str\' object has no attribute \'decode\'. Did you mean: \'encode\'?\n'] 
=================================================================================================
Compilation Error Files: ['atcoder_ABC051_A.py', 'atcoder_ABC120_C.py', 'codeforces_190_A.py', 'codeforces_92_A.py', 'codeforces_669_A.py', 'codeforces_569_A.py', 'atcoder_ABC127_B.py', 'atcoder_ABC178_A.py', 'atcoder_AGC046_A.py', 'atcoder_ABC124_C.py', 'codeforces_678_A.py', 'codeforces_96_B.py', 'codeforces_171_A.py', 'atcoder_ABC164_A.py', 'atcoder_ABC114_C.py', 'codeforces_546_A.py', 'codeforces_459_A.py', 'codeforces_32_B.py', 'atcoder_ABC153_A.py', 'atcoder_ARC062_B.py', 'atcoder_ABC149_C.py', 'atcoder_ABC142_A.py', 'atcoder_ABC042_A.py', 'atcoder_ABC125_A.py', 'codeforces_58_B.py', 'atcoder_ABC158_A.py', 'codeforces_651_A.py', 'codeforces_579_A.py', 'codeforces_147_A.py', 'codeforces_55_A.py', 'atcoder_ABC143_A.py', 'codeforces_8_B.py', 'codeforces_86_A.py', 'atcoder_ABC169_C.py', 'atcoder_AGC006_B.py', 'codeforces_379_A.py', 'atcoder_ABC174_C.py', 'atcoder_AGC007_C.py', 'codeforces_334_A.py', 'atcoder_ABC122_D.py', 'codeforces_678_B.py', 'atcoder_ABC151_A.py', 'codeforces_242_A.py', 'atcoder_ABC132_A.py', 'codeforces_369_B.py', 'atcoder_ABC139_B.py', 'atcoder_ABC158_B.py', 'codeforces_514_A.py', 'codeforces_110_B.py', 'atcoder_ABC170_A.py', 'atcoder_AGC025_A.py', 'codeforces_99_A.py', 'codeforces_544_B.py', 'codeforces_203_A.py', 'codeforces_79_A.py', 'atcoder_ARC102_C.py', 'codeforces_581_A.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_340_A.py'] 
=================================================================================================
