Total Instances: 86

Total Correct: 62
Total Runtime Failed: 17
Total Compilation Failed: 2
Total Test Failed: 4
Total Infinite Loop: 1

Accuracy: 72.09302325581395
Runtime Rate: 19.767441860465116
Compilation Rate: 2.3255813953488373
Test Failed Rate: 4.651162790697675
Infinite Loop Rate: 1.1627906976744187

=================================================================================================
Failed Test Files: ['atcoder_ABC155_E.py', 'codeforces_58_B.py', 'codeforces_96_B.py', 'atcoder_ARC062_B.py'] 
Failed Test Details: ['Filename: codeforces_96_B.py Actual: 4444477777\n Generated: 7444447777\n', 'Filename: atcoder_ABC155_E.py Actual: 1\n Generated: 0\n', 'Filename: atcoder_ARC062_B.py Actual: 0\n Generated: -1\n', 'Filename: codeforces_58_B.py Actual: 733035 \n244345 \n48869 \n1  Generated: 733035\n244345\n48869\n1\n'] 
=================================================================================================
Runtime Error Files: ['atcoder_ABC042_A.py', 'codeforces_203_A.py', 'atcoder_ABC168_C.py', 'codeforces_189_A.py', 'codeforces_544_B.py', 'atcoder_ABC122_D.py', 'atcoder_ABC169_C.py', 'codeforces_306_A.py', 'atcoder_ABC153_A.py', 'codeforces_171_A.py', 'atcoder_ABC127_B.py', 'atcoder_ABC051_A.py', 'codeforces_30_A.py', 'atcoder_ABC139_B.py', 'atcoder_ABC135_D.py', 'atcoder_ABC170_A.py', 'atcoder_ABC125_A.py'] 
Runtime Error Details: ['Filename: atcoder_ABC127_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC127_B.py", line 13, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC127_B.py", line 4, in main\n    r = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'2 1 2\\n\'\n', 'Filename: codeforces_306_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_306_A.py", line 40, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_306_A.py", line 32, in main\n    n, m = fr.next_double(), fr.next_double()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_306_A.py", line 15, in next_double\n    return float(self.next())\nValueError: could not convert string to float: \'87 34\'\n', 'Filename: atcoder_ABC139_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC139_B.py", line 16, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC139_B.py", line 4, in main\n    a = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'8 8\\n\'\n', 'Filename: atcoder_ABC170_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 17, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 8, in main\n    x = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'1 2 3 4 0\\n\'\n', 'Filename: codeforces_30_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_30_A.py", line 16, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_30_A.py", line 4, in main\n    A = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'7 896 7\\n\'\n', 'Filename: codeforces_203_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_203_A.py", line 29, in <module>\n    solver.solve(1, inp, out)\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_203_A.py", line 5, in solve\n    points = inp.readInt()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_203_A.py", line 23, in readInt\n    return int(self.stream.readline())\nValueError: invalid literal for int() with base 10: \'3 1 20 15 17 5\\n\'\n', 'Filename: atcoder_ABC122_D.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 37, in <module>\n    print(ins.calc())\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 11, in calc\n    return self.dfs(0, "TTT")\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 31, in dfs\n    if self.isOK(last3[1:] + c):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 18, in isOK\n    vals[i], vals[i + 1] = vals[i + 1], vals[i]\nIndexError: list index out of range\n', 'Filename: atcoder_ABC051_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 8, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 4, in main\n    a, b, c = input().split()\nValueError: not enough values to unpack (expected 3, got 1)\n', 'Filename: atcoder_ABC135_D.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC135_D.py", line 25, in <module>\n    dp[i][j] = dp[i-1][map[l]]\nKeyError: 12\n', 'Filename: atcoder_ABC169_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC169_C.py", line 11, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC169_C.py", line 4, in main\n    a = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'814793613347395 1.99\\n\'\n', 'Filename: atcoder_ABC153_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC153_A.py", line 16, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC153_A.py", line 4, in main\n    monsterHP = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'10000 1\\n\'\n', 'Filename: codeforces_189_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_189_A.py", line 16, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_189_A.py", line 4, in main\n    n = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'29 27 18 2\\n\'\n', 'Filename: atcoder_ABC125_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC125_A.py", line 13, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC125_A.py", line 4, in main\n    a = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'20 20 19\\n\'\n', 'Filename: codeforces_544_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_544_B.py", line 20, in <module>\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'100 10000\'\n', 'Filename: atcoder_ABC168_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC168_C.py", line 3, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'1 2 9 49\'\n', 'Filename: atcoder_ABC042_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/atcoder_ABC042_A.py", line 4, in <module>\n    num_1 = int(input())\nValueError: invalid literal for int() with base 10: \'5 5 7\'\n', 'Filename: codeforces_171_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/magicoder/avatar/java/python-sanitized/codeforces_171_A.py", line 8, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'35005211 521595368\'\n'] 
=================================================================================================
Compilation Error Files: ['codeforces_373_B.py', 'atcoder_AGC007_C.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_669_A.py'] 
=================================================================================================
