Total Instances: 86

Total Correct: 30
Total Runtime Failed: 37
Total Compilation Failed: 9
Total Test Failed: 9
Total Infinite Loop: 1

Accuracy: 34.883720930232556
Runtime Rate: 43.02325581395349
Compilation Rate: 10.465116279069768
Test Failed Rate: 10.465116279069768
Infinite Loop Rate: 1.1627906976744187

=================================================================================================
Failed Test Files: ['atcoder_ABC155_E.py', 'atcoder_ABC132_F.py', 'atcoder_ARC062_B.py', 'atcoder_ABC151_A.py', 'codeforces_110_B.py', 'codeforces_546_A.py', 'codeforces_58_B.py', 'codeforces_569_A.py', 'atcoder_ABC129_E.py'] 
Failed Test Details: ['Filename: codeforces_546_A.py Actual: 0\n Generated: 500499999999000\n', 'Filename: atcoder_ABC132_F.py Actual: 147\n Generated: 1000\n', 'Filename: atcoder_ARC062_B.py Actual: 0\n Generated: -1\n', 'Filename: atcoder_ABC129_E.py Actual: 63228815\n Generated: 956225049\n', 'Filename: codeforces_58_B.py Actual: 733035 \n244345 \n48869 \n1  Generated: 733035\n244345\n48869\n1\n', 'Filename: codeforces_110_B.py Actual: abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd Generated: abcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\n', 'Filename: atcoder_ABC151_A.py Actual: d\n Generated: 100\n', 'Filename: atcoder_ABC155_E.py Actual: 1\n Generated: inf\n', 'Filename: codeforces_569_A.py Actual: 5\n Generated: '] 
=================================================================================================
Runtime Error Files: ['atcoder_ABC153_A.py', 'atcoder_ABC070_B.py', 'atcoder_ABC042_A.py', 'atcoder_ABC122_D.py', 'codeforces_340_A.py', 'codeforces_678_A.py', 'codeforces_544_B.py', 'codeforces_651_A.py', 'codeforces_369_B.py', 'atcoder_ABC169_C.py', 'codeforces_379_A.py', 'atcoder_ABC114_C.py', 'atcoder_ABC143_A.py', 'atcoder_ABC168_C.py', 'atcoder_ABC125_A.py', 'atcoder_ABC120_C.py', 'atcoder_ABC127_B.py', 'codeforces_99_A.py', 'codeforces_8_B.py', 'codeforces_79_A.py', 'codeforces_171_A.py', 'codeforces_334_A.py', 'atcoder_ABC170_A.py', 'atcoder_ABC051_A.py', 'codeforces_203_A.py', 'atcoder_ABC124_A.py', 'codeforces_96_B.py', 'atcoder_ARC102_C.py', 'codeforces_147_A.py', 'atcoder_ABC132_A.py', 'atcoder_ABC149_B.py', 'atcoder_ABC178_B.py', 'atcoder_AGC006_B.py', 'codeforces_30_A.py', 'atcoder_ABC135_D.py', 'atcoder_ABC139_B.py', 'codeforces_306_A.py'] 
Runtime Error Details: ['Filename: codeforces_334_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_334_A.py", line 27, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_334_A.py", line 21, in main\n    print(odd.pop(0) + " " + (even.pop(-1)), end=" ")\nTypeError: unsupported operand type(s) for +: \'int\' and \'str\'\n', 'Filename: codeforces_379_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_379_A.py", line 3, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'80 970\'\n', 'Filename: atcoder_ABC132_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC132_A.py", line 57, in <module>\n    s = sc.next()\nAttributeError: \'dict\' object has no attribute \'next\'\n', 'Filename: atcoder_ABC120_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC120_C.py", line 3, in <module>\n    s1 = input().tochar()\nAttributeError: \'str\' object has no attribute \'tochar\'\n', 'Filename: atcoder_AGC006_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_AGC006_B.py", line 33, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_AGC006_B.py", line 5, in main\n    while sc.has_next_int():\nAttributeError: \'_io.TextIOWrapper\' object has no attribute \'has_next_int\'\n', 'Filename: atcoder_ARC102_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ARC102_C.py", line 8, in <module>\n    nchoosek[i][j] = (nchoosek[i - 1][j] + nchoosek[i - 1][j - 1]) % mod\nIndexError: list index out of range\n', 'Filename: atcoder_ABC143_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC143_A.py", line 3, in <module>\n    A = int(input())\nValueError: invalid literal for int() with base 10: \'75 25\'\n', 'Filename: atcoder_ABC168_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC168_C.py", line 18, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC168_C.py", line 4, in main\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'1 2 9 49\'\n', 'Filename: codeforces_340_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_340_A.py", line 34, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_340_A.py", line 31, in main\n    print(c)\nTypeError: a bytes-like object is required, not \'str\'\n', 'Filename: codeforces_306_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_306_A.py", line 14, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_306_A.py", line 6, in main\n    sys.stdout.write(str(int(input().strip().split()[0]) / int(input().strip().split()[1])) + " ")\nEOFError: EOF when reading a line\n', 'Filename: codeforces_8_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_8_B.py", line 38, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_8_B.py", line 4, in main\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'LUUDU\'\n', 'Filename: atcoder_ABC051_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 10, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 6, in main\n    a, b, c = map(str, scanner.readline().split(","))\nValueError: not enough values to unpack (expected 3, got 1)\n', 'Filename: codeforces_30_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_30_A.py", line 3, in <module>\n    A = int(input())\nValueError: invalid literal for int() with base 10: \'7 896 7\'\n', 'Filename: codeforces_99_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_99_A.py", line 1, in <module>\n    import java.util.stream\nModuleNotFoundError: No module named \'java\'\n', 'Filename: atcoder_ABC153_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC153_A.py", line 3, in <module>\n    monsterHP = int(input())\nValueError: invalid literal for int() with base 10: \'10000 1\'\n', 'Filename: codeforces_79_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_79_A.py", line 44, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_79_A.py", line 11, in main\n    with open(sys.stdin, \'r\') as br:\nTypeError: expected str, bytes or os.PathLike object, not TextIOWrapper\n', 'Filename: atcoder_ABC124_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC124_A.py", line 13, in <module>\n    print(solve())\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC124_A.py", line 4, in solve\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'6 6\'\n', 'Filename: atcoder_ABC114_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC114_C.py", line 4, in <module>\n    S = input()\nEOFError: EOF when reading a line\n', 'Filename: atcoder_ABC125_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC125_A.py", line 3, in <module>\n    n, k, m, l, a, b, c = map(int, sys.stdin.readlines())\nValueError: invalid literal for int() with base 10: \'20 20 19\\n\'\n', 'Filename: codeforces_544_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_544_B.py", line 22, in <module>\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'100 10000\'\n', 'Filename: atcoder_ABC170_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 14, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 4, in main\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'1 2 3 4 0\'\n', 'Filename: atcoder_ABC070_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC070_B.py", line 3, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'0 50 50 100\'\n', 'Filename: codeforces_203_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_203_A.py", line 41, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_203_A.py", line 7, in main\n    solver.solve(1, input, output)\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_203_A.py", line 11, in solve\n    points = int(input.readline())\nValueError: invalid literal for int() with base 10: \'3 1 20 15 17 5\\n\'\n', 'Filename: codeforces_96_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_96_B.py", line 32, in <module>\n    codeforces_96_B()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_96_B.py", line 21, in codeforces_96_B\n    arr = [int(x) for x in input().split()]\nEOFError: EOF when reading a line\n', 'Filename: codeforces_147_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_147_A.py", line 18, in <module>\n    sb = StringBuilder()\nNameError: name \'StringBuilder\' is not defined\n', 'Filename: codeforces_651_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_651_A.py", line 24, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_651_A.py", line 4, in main\n    num1 = int(input())\nValueError: invalid literal for int() with base 10: \'100 25\'\n', 'Filename: codeforces_171_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_171_A.py", line 17, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_171_A.py", line 4, in main\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'35005211 521595368\'\n', 'Filename: atcoder_ABC139_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC139_B.py", line 3, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'8 8\'\n', 'Filename: atcoder_ABC178_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC178_B.py", line 3, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'418379342 802780784 -790013317 -445130206\'\n', 'Filename: codeforces_369_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_369_B.py", line 21, in <module>\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'1 1 1 1 1 1\'\n', 'Filename: atcoder_ABC122_D.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 34, in <module>\n    ins = atcoder_ABC122_D()\nNameError: name \'atcoder_ABC122_D\' is not defined\n', 'Filename: atcoder_ABC135_D.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC135_D.py", line 22, in <module>\n    l = j - (ch - \'0\')\nTypeError: unsupported operand type(s) for -: \'str\' and \'str\'\n', 'Filename: atcoder_ABC169_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC169_C.py", line 12, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC169_C.py", line 5, in main\n    a = int(sc.readline())\nValueError: invalid literal for int() with base 10: \'814793613347395 1.99\\n\'\n', 'Filename: atcoder_ABC127_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC127_B.py", line 3, in <module>\n    r = int(input())\nValueError: invalid literal for int() with base 10: \'2 1 2\'\n', 'Filename: atcoder_ABC042_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC042_A.py", line 27, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC042_A.py", line 5, in main\n    num_1 = int(input())\nValueError: invalid literal for int() with base 10: \'5 5 7\'\n', 'Filename: codeforces_678_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/codeforces_678_A.py", line 1, in <module>\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'999999999 1\'\n', 'Filename: atcoder_ABC149_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/mistral/avatar/java/python-sanitized/atcoder_ABC149_B.py", line 3, in <module>\n    A = int(input())\nValueError: invalid literal for int() with base 10: \'1000000000000 1000000000000 1000000000000\'\n'] 
=================================================================================================
Compilation Error Files: ['codeforces_242_A.py', 'codeforces_459_A.py', 'codeforces_514_A.py', 'codeforces_190_A.py', 'atcoder_AGC002_A.py', 'codeforces_678_B.py', 'codeforces_189_A.py', 'atcoder_AGC034_B.py', 'atcoder_AGC007_C.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_669_A.py'] 
=================================================================================================
