Total Instances: 81

Total Correct: 24
Total Runtime Failed: 3
Total Compilation Failed: 50
Total Test Failed: 3
Total Infinite Loop: 1

Accuracy: 29.629629629629626
Runtime Rate: 3.7037037037037033
Compilation Rate: 61.72839506172839
Test Failed Rate: 3.7037037037037033
Infinite Loop Rate: 1.2345679012345678

=================================================================================================
Failed Test Files: ['codeforces_514_A.py', 'atcoder_AGC002_A.py', 'codeforces_30_A.py'] 
Failed Test Details: ['Filename: codeforces_30_A.py Actual: 2\n Generated: 128\n', 'Filename: atcoder_AGC002_A.py Actual: Positive\n Generated: Negative\n', 'Filename: codeforces_514_A.py Actual: 4221\n Generated: 4221.0\n'] 
=================================================================================================
Runtime Error Files: ['codeforces_189_A.py', 'atcoder_ABC114_C.py', 'atcoder_ABC168_C.py'] 
Runtime Error Details: ['Filename: atcoder_ABC168_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/wizardcoder/avatar/java/python-sanitized/atcoder_ABC168_C.py", line 3, in <module>\n    a, b = map(int, input().split())\nValueError: too many values to unpack (expected 2)\n', 'Filename: atcoder_ABC114_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/wizardcoder/avatar/java/python-sanitized/atcoder_ABC114_C.py", line 14, in <module>\n    S = input()\nEOFError: EOF when reading a line\n', 'Filename: codeforces_189_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/wizardcoder/avatar/java/python-sanitized/codeforces_189_A.py", line 24, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/wizardcoder/avatar/java/python-sanitized/codeforces_189_A.py", line 12, in main\n    n = in_.nextInt()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/wizardcoder/avatar/java/python-sanitized/codeforces_189_A.py", line 8, in nextInt\n    return int(self.stream.readline().strip())\nValueError: invalid literal for int() with base 10: \'29 27 18 2\'\n'] 
=================================================================================================
Compilation Error Files: ['codeforces_459_A.py', 'codeforces_86_A.py', 'codeforces_581_A.py', 'codeforces_334_A.py', 'atcoder_ABC174_C.py', 'atcoder_ABC120_C.py', 'codeforces_651_A.py', 'codeforces_569_A.py', 'codeforces_546_A.py', 'atcoder_ABC170_A.py', 'codeforces_242_A.py', 'atcoder_ABC125_A.py', 'atcoder_ABC178_A.py', 'codeforces_92_A.py', 'codeforces_79_A.py', 'codeforces_369_B.py', 'codeforces_96_B.py', 'atcoder_ABC122_D.py', 'atcoder_ABC127_B.py', 'atcoder_ARC102_C.py', 'atcoder_ARC062_B.py', 'codeforces_32_B.py', 'codeforces_203_A.py', 'codeforces_55_A.py', 'atcoder_ABC169_C.py', 'atcoder_AGC025_A.py', 'codeforces_147_A.py', 'atcoder_ABC051_A.py', 'atcoder_ABC124_C.py', 'codeforces_99_A.py', 'codeforces_678_A.py', 'atcoder_ABC139_B.py', 'codeforces_58_B.py', 'codeforces_8_B.py', 'atcoder_AGC007_C.py', 'atcoder_ABC132_A.py', 'codeforces_544_B.py', 'codeforces_678_B.py', 'atcoder_ABC142_A.py', 'codeforces_110_B.py', 'atcoder_ABC143_A.py', 'codeforces_669_A.py', 'atcoder_ABC164_A.py', 'codeforces_579_A.py', 'codeforces_190_A.py', 'atcoder_AGC006_B.py', 'codeforces_171_A.py', 'atcoder_AGC046_A.py', 'atcoder_ABC158_A.py', 'atcoder_ABC151_A.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_340_A.py'] 
=================================================================================================
